---
- hosts: kubernetes_master_nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Export join token as script
    shell: grep -A 2 'kubeadm join' kubeadm_logs> joincommand.sh
  - name: Copy to the command machine
    fetch: src=joincommand.sh dest=/tmp/joincommand.sh

- hosts: kubernetes_worker_nodes
  tasks:
  - name:
    copy: src=/tmp/joincommand.sh/k8master/joincommand.sh dest=$HOME/joincommand.sh
  - name: make it execute
    shell: chmod +x $HOME/joincommand.sh

  - name: Joining worker nodes with kubernetes master
    become: yes
    shell: ./joincommand.sh 
