...

- hosts:
  localhost:
   vars:
     ansible_connection: local
  become: true
  
  tasks:
  - name: Creating .kube directory
    file: 
      path: /home/lab/.kube
      state: directory

  - name: Copying kubeconfig files 
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/lab/.kube/config
      owner: lab
      group: lab
      remote_src: yes
    become: yes
    delegate_to: k8master


