---
- hosts: all
  vars_files: 
  - env_variables
  become: yes
  
  tasks:
  - name: copy hosts file 
    copy: src=~/K8s/Kubernetes-CLuster-creation/Fedora/playbooks/hostnames dest=/etc/hosts
    delegate_to: localhost

  - name: Update hosts file in /etc/hosts
    copy: 
      src: /etc/hosts
      dest: /etc/hosts 
        
  - name: Set variable for IP address in host file and new host name
    shell: ip4=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1); export newhostname=$(grep $ip4 /etc/hosts | awk '{print $3}'); hostnamectl set-hostname $newhostname
         
  - name: upgrade all packages
    dnf:
       name: '*'
       state: latest
     
  - name: Rebooting hosts 
    reboot:
      msg: "Reboot initiated"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami



