...

- hosts:
  localhost:
   vars:
     ansible_connection: local
  become: yes
 
  tasks:
  - name: Download requirements for kubespray
    shell: sudo pip3 install -r requirements.txt
  - name: Copy the inventory sample file 
    shell: cp -rfp inventory/sample inventory/mycluster
  - name: Declare the variables for the inventory builder
    shell: declare -a IPS=(192.168.1.2 192.168.1.3 192.168.1.4)
  - name: Create the config file
    shell: CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
  - name: Print the next command to run for easy pasting  
    shell: echo "ansible-playbook -i inventory/mycluster/hosts.yaml  --become --become-user=root cluster.yml --ask-become-pass"



