---
- hosts: kubernetes_master_nodes
  become: true
  vars_files:
  - env_variables 
  tasks:

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}} > kubeadm_logs
    register: output
    become: true

  - name: Creating .kube directory
    file: 
      path: /home/lab/.kube
      state: directory

  - name: Copying kubeconfig files 
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/lab/.kube/config
      owner: lab
      group: lab
      remote_src: yes
    become: yes
 
  - name: Installing Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    become_user: lab


