---
- hosts: kubernetes_master_nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Export join token as script
    shell: grep -A 2 'kubeadm join' kubeadm_logs> joincommand.sh
  - name: Copy to the command machine
    fetch: src=joincommand.sh dest=/tmp/joincommand.sh

- hosts: kubernetes_worker_nodes
  tasks:
  - name: Workers copy Join token and command script from Ansible controller
    copy: src=/tmp/joincommand.sh/k8smaster/joincommand.sh dest=$HOME/joincommand.sh
 
  - name: Make the script executable
    shell: chmod +x $HOME/joincommand.sh

  - name: Joining worker nodes with kubernetes master
    become: yes
    shell: ./joincommand.sh 
