---
- hosts: all
  vars_files: 
  - env_variables
  become: yes
  
  tasks:
  - name: Update hosts file in /etc/hosts
    copy: 
      src: /etc/hosts
      dest: /etc/hosts 
        
  - name: Set variable for IP address in host file and new host name
    shell: ip4=$(/sbin/ip -o -4 addr list enp0s3 | awk '{print $4}' | cut -d/ -f1); export newhostname=$(grep $ip4 /etc/hosts | awk '{print $3}'); hostnamectl set-hostname $newhostname
       
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'
     
  - name: Create new file in boot config for kernel modules
    file:
     path: /etc/modules-load.d/crio.conf
     state: touch

  - name: Add br_netfilter and overlay kernel modules to bootup config
    blockinfile:
     path: /etc/modules-load.d/crio.conf
     block: | 
        overlay
        br_netfilter

  - name: Loading kernel module br_netfilter
    shell: modprobe br_netfilter
    become: yes
      
  - name: Loading kernel module overlay
    shell: modprobe overlay
    become: yes 

  - name: Add config file to set kernel module parameters
    file:
     path: /etc/sysctl.d/99-kubernetes-cri.conf
     state: touch

  - name: Set up required sysctl params
    blockinfile:
     path: /etc/sysctl.d/99-kubernetes-cri.conf
     block: | 
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1

  - name: Rebooting hosts 
    reboot:
      msg: "Reboot initiated"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
